export type RootStackParamList = {
  SPLASH_SCREEN: undefined;
  HOME_SCREEN: undefined;
  PET_SCREEN: undefined;
  BOTTOM_TAB_NAVIGATOR: undefined;
  SEARCH_SCREEN: undefined;
  EXPLORE_SCREEN: undefined;
  PROFILE_SCREEN: undefined;
  DRAWER_NAVIGATOR: undefined;
};

export const ROUTE = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PET_SCREEN: 'PET_SCREEN',
  BOTTOM_TAB_NAVIGATOR: 'BOTTOM_TAB_NAVIGATOR',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  EXPLORE_SCREEN: 'EXPLORE_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  DRAWER_NAVIGATOR: 'DRAWER_NAVIGATOR',
};
